[programs.localnet]
nft = "H2EyigeZP5uwVLf83PevyJ1FMUmXsx64N46qHs3S41Eh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 /app/nft/tests"
